version: '3.8'

services:
  # Ollama service - runs the LLM backend
  ollama:
    image: ollama/ollama:latest
    container_name: grammar-fixer-ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - grammar-fixer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  # Grammar Fixer application service
  grammar-fixer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grammar-fixer-app
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=gemma3
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - grammar-fixer-network
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: false
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  grammar-fixer-network:
    driver: bridge

volumes:
  ollama-data:
    driver: local
