name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Verify code structure
      run: |
        echo "Verifying project structure..."
        test -f package.json || exit 1
        test -f src/index.js || exit 1
        test -f src/grammarFixer.js || exit 1
        test -d tests || exit 1
        echo "✓ Project structure verified"
    
    - name: Run tests with mock LLM
      run: npm test
    
    - name: Run tests with coverage
      run: npm run test:coverage
      if: matrix.node-version == '20.x'
    
    - name: Upload coverage to artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '20.x'
      with:
        name: coverage-report
        path: coverage/
        retention-days: 7
    
    - name: Check for high coverage
      if: matrix.node-version == '20.x'
      run: |
        echo "Coverage report generated successfully"
        if [ -d "coverage" ]; then
          echo "✓ Coverage directory exists"
        fi
